name: Deploy To EC2


on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest  # ubuntu 환경 / 가장 최신 버전(latest)
    steps:
      - name: Github Repository에서 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        run: |
          mkdir -p ./src/main/resources
          printf '%s' "$APPLICATION_PROPERTIES" > ./src/main/resources/application.yml
      
      
      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: 테스트 및 빌드하기
        run: |
          ./gradlew clean build || (cat ./build/reports/tests/test/index.html && exit 1)

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar    # 빌드 파일 이름 project.jar로 변경

      - name: EC2에 new 디렉터리 생성하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            mkdir -p /home/ubuntu/SUDA/new

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/SUDA/new  #파일을 저장할 장소


      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true # 스크립트 실패할경우 즉시 워크플로우 종료
          script: |
            echo "Stopping any running application on port 8080..."
            sudo fuser -k -n tcp 8080 || true

            echo "Preparing deployment directories..."
            rm -rf /home/ubuntu/SUDA/current
            mkdir -p /home/ubuntu/SUDA/current

            echo "Deploying new jar file..."
            mv /home/ubuntu/SUDA/new/project.jar /home/ubuntu/SUDA/current/project.jar

            echo "Starting application..."
            cd /home/ubuntu/SUDA/current
            nohup java -jar project.jar > ./nohup.out 2>&1 &

            echo "Cleaning up temporary files..."
            rm -rf /home/ubuntu/SUDA/new
